# docker-compose.yml
version: '3.8'

services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db

  # client:
  #   build: ./client
  #   ports:
  #     - "3000:3000"

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: homeworkdb
    ports:
      - "5485:5432"
