"""change:table comments

Revision ID: d42276d5a6dd
Revises: bdc4e2f77923
Create Date: 2024-09-03 10:33:07.999788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd42276d5a6dd'
down_revision = 'bdc4e2f77923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
